---
- name: Create temporary file for job vars
  tempfile:
    state: file
  register: r_job_vars_temp

- name: Write job vars to temp file
  copy:
    dest: "{{ r_job_vars_temp.path }}"
    content: >-
      {{ ( vars.job_vars | default({}) | combine(secrets  | default({})) ) | to_nice_yaml }}

- name: "Launch requested Job {{ job_template_name }}"
  tower_job_launch:
    job_template:     "{{ job_template_name }}"
    inventory:        "empty-inventory-{{ job_vars['__meta__']['tower']['run_group'] | default('default') }}"
    extra_vars: "@{{ r_job_vars_temp.path }}"
  register:       r_tower_job_launch

- name: Remove temporary file for job vars
  file:
    state: absent
    path: "{{ r_job_vars_temp.path }}"

- name: Callback with job started event
  include_role:
    name: job_callback
  vars:
    job_callback_stage: main
    job_callback_event: started
    job_callback_message: >-
      {{ job_vars['__meta__']['tower']['action'] }}-{{ job_vars['__meta__']['deployer']['type'] }}-{{ job_vars['__meta__']['deployer']['scm_ref'] }}
    job_callback_data: "{{ r_tower_job_launch }}"

- when: job_vars.__meta__.deployer.wait | default(true) | bool
  include_tasks: wait-for-job.yml
  vars:
    _tower_job_id: "{{ r_tower_job_launch.id }}"
...
